[package]
name = "rustlox"
version = "0.1.0"
authors = ["nitta-kazuki <nitta-kazuki@dmm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
